server:
  port: 8080
  servlet:
    context-path: /


spring: 
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://noveldb.cmgwmuioofp3.ap-northeast-2.rds.amazonaws.com:3306/novel
    username: admin
    password: a1s2d3f4g5
  jpa :
    open-in-view: false
    properties :
      hibernate : 
          format_sql :true
    show-sql : true
    hibernate :
      ddl-auto : validate
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    

mybatis:
  mapper-locations: classpath:mapper/*.xml

JWT:
  ISSUER: TEST
  SECRET: SeCrEt1938yh0r8ehgi0923hnr0qiu123e12r51028





  
cloud:
  aws:
    credentials:
      accessKey: AKIAUX4ZADFPUKVDE4TY
      secretKey: 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
    s3:
      bucket: prj-novel
    region:
      static: ap-northeast-2
    stack:
      auto: false