sever:
  port: 8080
  


spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://noveldatabase.cmgwmuioofp3.ap-northeast-2.rds.amazonaws.com:3306/novel
    username: admin
    password: 123456789

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  ISSUER: TEST
  SECRET: SeCrEt1938yh0r8ehgi0923hnr0qiuaShInG